[config]

[config.wallpaper]
command = "swww"
arguments = ["img", "--transition-type", "grow", "--transition-duration", "1"]
set = true

[templates.quickshell]
input_path = 'templates/QS.qml'
output_path = '~/.config/quickshell/services/Colors.qml'

[templates.kitty]
input_path = 'templates/kitty-colors.conf'
output_path = '~/.config/kitty/colors.conf'
post_hook = 'pkill -SIGUSR1 kitty'

[templates.starship]
input_path = 'templates/starship-colors.toml'
output_path = '~/.config/starship.toml'

[templates.hyprland]
input_path = 'templates/hyprland-colors.conf'
output_path = '~/.config/hypr/hyprland/colors.conf'
post_hook = 'hyprctl reload'

[templates.wlogout]
input_path = 'path/to/template'
output_path = '~/.config/wlogout/colors.css'
